# Generated by Django 4.2.5 on 2023-12-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follow_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='user',
        ),
    ]
