# Generated by Django 4.2.5 on 2023-12-29 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_follow_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='liked_user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='Liked', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
