# Generated by Django 4.2.5 on 2023-12-29 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_posts_likes_posts_liked_user_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='liked_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
