# Generated by Django 4.2.5 on 2024-01-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_posts_like_delete_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
