# Generated by Django 4.2.5 on 2023-10-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, default='https://i.ibb.co/4pG5hBD/noimage.png', max_length=1000),
        ),
    ]
